### ISSUE TITLE
Thanks for your wrok, and some requests

### ISSUE THREAD

**Issue by YZYZYZGOD** [turtle-insect/MonsterHunterStories2#1]
Thanks for your work, and I sincerely hope that you can add Chinese support to this software. Of course, I'v got a Chinese version Item.txt from your original document.  
And I found an error, if add item No.34, it will be strange in the game, like this [![R7gbMn.jpg](https://z3.ax1x.com/2021/07/07/R7gbMn.jpg)](https://imgtu.com/i/R7gbMn)  
We also need a function to add material.  
Thanks for your woork again, and hope you happy every day.
[item.txt](https://github.com/turtle-insect/MonsterHunterStories2/files/6772089/item.txt)

**Comment by YZYZYZGOD** [comment]
Acyually I also want to know how you get the item.txt which contain itemName and itemID, I try to extract MHST2 Full game XCI, and get some files included some message.arc, and after some trying I confirm ItemID , ItemName, equipmentName and etc. are in these files for diffierent languages, so if you know how to unpack these message.arc files, I seriously hope you can tell me hou to do it ,plz.

**Comment by YZYZYZGOD** [comment]
I'v know that monster material ID has a little change in savedata, you should add 720 for original ID

**Comment by iSharingan** [comment]
the behavior appears to stem from missing item data or an incorrectly formatted offset jump. 4294967295 is 0xFFFFFFFF in hex, so the quantity may have actually been written to the item ID instead (0xFFFFFFFF being the default value for quantity when an item has not been found previously)

**Comment by YZYZYZGOD** [comment]
> 该行为似乎源于缺少项目数据或格式不正确的偏移跳转。4294967295 是十六进制的 0xFFFFFFFF，因此数量实际上可能已写入项目 ID（0xFFFFFFFF 是先前未找到项目时数量的默认值）



> 我知道怪物材质ID在savedata上有一点变化，你应该为原始ID添加720

from IT_MONSTER_MATERIAL_506, should add 986,IT_AMULETS add 432,

**Comment by turtle-insect** [comment]
I believe the correct number is No.36, not No.34.
I've corrected the item.txt file.

**Comment by Rafario448** [comment]
I also want to thank you for the editor, it saved a casual player like me tons of grinding, playing the full version on Yuzu emulator
