### ISSUE TITLE
Add monster Gene   

### ISSUE THREAD

**Issue by jim972329667** [turtle-insect/MonsterHunterStories2#12]
The first Gene is about   ReadNumber(mAddress + 332, 4);
There are nine of Gene, four bytes each
![2021071620251301-F6B820094E3994C4623B594036FE6481](https://user-images.githubusercontent.com/59948910/125948291-ad7bbcaa-3152-4bf7-b14e-e29f0dc00655.jpg)

**Comment by jim972329667** [comment]
![20210716203623](https://user-images.githubusercontent.com/59948910/125948915-d2892f07-23e4-419b-86fc-a70b49fd6829.png)

**Comment by jim972329667** [comment]
For the weapon type  ^v^

           `public uint WeaponsType      
		//0 is Sword&Shield, 1 is Great Sword, 2 is Hammer, 3 is Hunting Horn, 4 is Bow, 5 is Gunlance
		{
			get { return SaveData.Instance().ReadNumber(mAddress, 2); }
			set
			{
				SaveData.Instance().WriteNumber(mAddress, 2, value);
				PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Type)));
			}
		}
        
		public uint WeaponsID     
		{
			get { return SaveData.Instance().ReadNumber(mAddress + 2, 2); }
			set { Util.WriteNumber(mAddress + 2, 2, value, 1, 0xFFFF); }
		}

		public uint WeaponsLv        //max is 3
		{
			get { return SaveData.Instance().ReadNumber(mAddress + 4, 1); }
			set { Util.WriteNumber(mAddress + 4, 1, value, 1, 0x03); }
		}`

**Comment by jim972329667** [comment]
Update the ARMOR_ADDRESS and TALISMANS_ADDRESS

`	
        //0 is Sword&Shield, 1 is Great Sword, 2 is Hammer, 3 is Hunting Horn, 4 is Bow, 5 is Gunlance
	public const uint WEAPON_ADDRESS = 0x3ECC;
        public const uint WEAPON_COUNT = 700;
        public const uint WEAPON_SIZE = 36;
	//Type 06
        public const uint ARMOR_ADDRESS = 0xA13C;
        public const uint ARMOR_COUNT = 400;
        public const uint ARMOR_SIZE = 36;
	//Type 07
	public const uint TALISMANS_ADDRESS = 0xD97C;
	public const uint TALISMANS_COUNT = 200;
	public const uint TALISMANS_SIZE = 48;
`

![code](https://user-images.githubusercontent.com/59948910/125960210-aba27d3f-6789-4f7b-a4d1-6b3f3445a8ad.png)

**Comment by turtle-insect** [comment]
Thank you

https://github.com/turtle-insect/MonsterHunterStories2/commit/591f05b97921c05a9164a52d52bc97de850c026f

**Comment by jim972329667** [comment]
> Thank you
> 
> [591f05b](https://github.com/turtle-insect/MonsterHunterStories2/commit/591f05b97921c05a9164a52d52bc97de850c026f)

I'm glad I could help. I hope to make it better.

**Comment by jim972329667** [comment]
Egg Address

public const uint EGG_ADDRESS = 0x10CAC; //??? 0x10C4A
public const uint EGG_COUNT = 12;
public const uint EGG_SIZE = 120;

**Comment by jim972329667** [comment]
![Egg](https://user-images.githubusercontent.com/59948910/126040709-3e905b3b-2423-48a2-880a-c003fda6ac2f.png)
