### ISSUE TITLE
Add bottle caps

### ISSUE THREAD

**Issue by WilliamKL2** [turtle-insect/MonsterHunterStories2#13]
the save editor only has money edit but not bottle cap edit, it will be nice if has

**Comment by CaelThunderwing** [comment]
> 
> 
> the save editor only has money edit but not bottle cap edit, it will be nice if has

you can .. Sorta by adding via Item List, granted it Should be a option on the Basic Tab with Money  n all.

**Comment by WilliamKL2** [comment]
its on item list? what the name?
