### ISSUE TITLE
Add more monster list

### ISSUE THREAD

**Issue by kukaram** [turtle-insect/MonsterHunterStories2#15]
my monster list shown in this editor only 199,
Maximum is 500.

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/MonsterHunterStories2/issues/7

https://github.com/turtle-insect/MonsterHunterStories2/blob/520b35a8b3d70961ae1fe693cfe4ebd39211e357/MonsterHunterStories2/Util.cs#L10

**Comment by turtle-insect** [comment]
Thank you!
