### ISSUE TITLE
Gene ID list.

### ISSUE THREAD

**Issue by DevBlocker** [turtle-insect/MonsterHunterStories2#16]
Can we get a gene ID list? With the types and elements labeled, and maybe which monstie it belongs to originally. And can you please make the gene system as a 3x3 grid as in the game. It would help a lot to make bingos. Thank you.

**Comment by jim972329667** [comment]
From left to right from top to bottom.
![20210717153236](https://user-images.githubusercontent.com/59948910/126029820-4452e141-015e-4a56-9d55-4a5b3e1d0ce4.png)

**Comment by mfadhilt07** [comment]
could u make a list of id on each genes in a text file in order pleaseee? just like you did on item list. thx before

**Comment by jim972329667** [comment]
https://docs.google.com/spreadsheets/d/1QzM9X34IfACPtRa_yWq2BZUidWJqs0l2K_Gs2023bO0

**Comment by DevBlocker** [comment]
Thanks jim972329667.

**Comment by mfadhilt07** [comment]
omg jim972329667 thankyou so muchhhh broo. it helps a lott dudeee. hoping that god always bless u broo
