### ISSUE TITLE
PC Save Support

### ISSUE THREAD

**Issue by HaroPla** [turtle-insect/MonsterHunterStories2#17]
Hello, If possible I'd like to request pc save file support since it looks like a lot of people are having trouble in converting their savefile.

**Comment by turtle-insect** [comment]
Thank you!!
but I don't have PC game.

**Comment by HaroPla** [comment]
Hello, I have savefile if you want? Maybe you can use it as basis for their difference?

**Comment by HaroPla** [comment]
Sorry, I accidentaly closed it, I have a save for pc, maybe you can use it to compare the savefile?
