### ISSUE TITLE
Sell mod service

### ISSUE THREAD

**Issue by Khokhex** [turtle-insect/MonsterHunterStories2#2]
Hi,  do you sell modificación save file for person. I really interested in this posibility.

**Comment by turtle-insect** [comment]
Hi,
I will not sell.
Donations will be accepted.

**Comment by Khokhex** [comment]
OK no problem. How I do it to donate to you and so that you can help me in
my account.

**Comment by turtle-insect** [comment]
thank you!

If you would like to donate, we would be happy to give me an amazon gift
<mail : turtle.insect@gmail.com>
