### ISSUE TITLE
Savedata corrupted

### ISSUE THREAD

**Issue by MuryMH** [turtle-insect/MonsterHunterStories2#26]
I'm on PC, I decrypted my save with Asterisk tools, edit it and encrypted it again with Asterisk tools too, but when I launch the game it says my savedata is corrupted. How I can fix that please ?

**Comment by turtle-insect** [comment]
> edit it

What happens if I only perform decrypted and encrypted?

**Comment by MuryMH** [comment]
> > edit it
> 
> What happens if I only perform decrypted and encrypted?

The logiciel close without saying anything, I assume it encrypted the save but I can't really know

**Comment by jim972329667** [comment]
Before encrypted，make sure the first byte is 0x01
![image](https://user-images.githubusercontent.com/59948910/126356105-359e7e0f-cccd-4a43-8846-051a9599ff2a.png)

**Comment by MuryMH** [comment]
> Before encrypted，make sure the first byte is 0x01
> ![image](https://user-images.githubusercontent.com/59948910/126356105-359e7e0f-cccd-4a43-8846-051a9599ff2a.png)

Where can I see this please ?

**Comment by jim972329667** [comment]
https://github.com/solemnwarning/rehex/releases/tag/0.3.91

**Comment by MuryMH** [comment]
> https://github.com/solemnwarning/rehex/releases/tag/0.3.91

![image](https://user-images.githubusercontent.com/87701551/126362956-b677f816-2c62-4aaf-aeaa-5e6834b50512.png)
When I launch rehex I don't have the same window as u, how did u do that please ?

**Comment by HaroPla** [comment]
Try using Ultraedit software

**Comment by Akzyra** [comment]
MuryMH is using [HxD](https://mh-nexus.de/en/hxd/)
And the file you are viewing is encrypted. Decrypt, make edits with this tool, then encrypt it again.

**Comment by jim972329667** [comment]
* First，Decrypt your PC save file.
* Second, Open your decrypted save file with "PC?" button.
<img src="https://user-images.githubusercontent.com/59948910/126407626-065e2054-7fd3-4fe5-b7e2-94bc93afaeff.png" width = "200" height = "150" alt="" align=center />

* Third, Check the first byte when the modification is completed. (Only Swicth Convert PC Save or PC Convert Swicth Need) 
 Switch save file the first byte is 0x00, PC save file the first byte is 0x01.
* Fourth, Encrypt your save file, Don't forget your steam ID64. (It is necessary)

**Comment by MuryMH** [comment]
> * First，Decrypt your PC save file.
> * Second, Open your decrypted save file with "PC?" button.
> 
> <img alt="" width="200" height="150" src="https://user-images.githubusercontent.com/59948910/126407626-065e2054-7fd3-4fe5-b7e2-94bc93afaeff.png">
> 
> * Third, Check the first byte when the modification is completed. (Only Swicth Convert PC Save or PC Convert Swicth Need)
>   Switch save file the first byte is 0x00, PC save file the first byte is 0x01.
> * Fourth, Encrypt your save file, Don't forget your steam ID64. (It is necessary)

It work, thank u very much !

**Comment by iSharingan** [comment]
> It work, thank u very much !

closing this issue
