### ISSUE TITLE
Changing level of Monstie and cahracter stops experience gain

### ISSUE THREAD

**Issue by Dooch88** [turtle-insect/MonsterHunterStories2#3]
After changing the level of my main character and monsters they stopped gaining experience.

**Comment by iSharingan** [comment]
Assuming this works like the first game (which is almost certain based on this behavior), its because the level is calculated based on the total Exp accumulated. editing level means you need to "catch up" your exp total to continue leveling up

**Comment by turtle-insect** [comment]
Experience can be modified in version 0.06.

**Comment by Dooch88** [comment]
Thanks so much!
