### ISSUE TITLE
Character and Monstie not leveling up

### ISSUE THREAD

**Issue by Spakauskie** [turtle-insect/MonsterHunterStories2#30]
After messing with the levels, like adding +1 on the level, they won't level up anymore. they would level with the exp screen but it won't reflect the character.

**Comment by iSharingan** [comment]
Dont edit your level. Edit the experience. If you edit your level, the exp has to "catch up" before you'll level up again.

Duplicate with #3

**Comment by Spakauskie** [comment]
Thanks for the info. Closing this one.😁✌️
