### ISSUE TITLE
English item.txt file?

### ISSUE THREAD

**Issue by HenryHeliolisk** [turtle-insect/MonsterHunterStories2#4]
Trying to decipher certain items using a translator, but most come up unrecognizable, is there any way fro there to be an english translation of the items? or referme to a list or something like that?

**Comment by turtle-insect** [comment]
multi langage support in ver 0.10

you update google Spreadsheet
https://docs.google.com/spreadsheets/d/1ePQdOEW_MQfNVqc3drSmGQN_wdaOAljhINBGiRgggxY/edit#gid=0
