### ISSUE TITLE
issue with exp digits

### ISSUE THREAD

**Issue by tomdal** [turtle-insect/MonsterHunterStories2#6]
on the monster.cs and character.cs, the integer size needs to be 5 because the exp grows to be that size for example level 86 exp is 30565612.

set { Util.WriteNumber(mAddress + 336, 5, value, 0, 99999999); }

**Comment by turtle-insect** [comment]
thank you.
https://github.com/turtle-insect/MonsterHunterStories2/commit/a3fca7906f7899e86c575b35c5b5933adb79c401
