### ISSUE TITLE
Something is wrong with my monster list after game updated

### ISSUE THREAD

**Issue by KunFrancis** [turtle-insect/MonsterHunterStories2#7]
After I installed new game update yesterday, my monster list shown in this editor never chanded anymore. 
Even I caught a lot of new monsters, the list still remain unchanged.

**Comment by DevBlocker** [comment]
It's not because of the game, it's the current limit of the list. He has to edit the code to show more monsties in the list.

**Comment by turtle-insect** [comment]
thank you.

https://github.com/turtle-insect/MonsterHunterStories2/blob/cdd058e409f965a64b2e80ab62157471ae7c2b58/MonsterHunterStories2/Util.cs#L10

Do you know Max value?

**Comment by DevBlocker** [comment]
After purchasing all the stable updates it becomes 200. So I guess 200 is the max value.

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/MonsterHunterStories2/blob/5a1e5c0dad4022b7ebe395cc46fe4fa90486ec43/MonsterHunterStories2/Util.cs#L10

**Comment by DevBlocker** [comment]
Thank you for your work.
